contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #nfcore_fragmentomics channel"
    url: https://nfcore.slack.com/channels/nfcore_fragmentomics
    about: Discussion about the ejc043/nfcore_fragmentomics pipeline
